---
title: "data_analysis"
author: "finn krauss"
date: "2025-05-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

## Load Packages

```{r}
setwd("~/R Studio/NSAS Herring/NSAS-Herring")

library(bcp)
library(changepoint)
library(ggrepel)
library(readxl)
library(ggplot2)
library(tidyverse)
library(FSA)
library(strucchange)
library(MASS)
library(hydroGOF)
library(mgcv)
library(INDperform)
library(dplyr)
library(purrr)
library(progress)
library(segmented)
library(FLCore)
library(gridExtra)
```

## Import data

```{r}
load("data/Herring_LAI.Rdata")

### Load functions from "functions"
source("R/functions.R")

### Split data into components
Herring <- list()
Herring$SHOR <- Herring_LAI[Herring_LAI$component == "Shetland_Orkney",]
Herring$Buchan <- Herring_LAI[Herring_LAI$component == "Buchan",]
Herring$Banks <- Herring_LAI[Herring_LAI$component == "Banks",]
Herring$Downs <- Herring_LAI[Herring_LAI$component == "Downs",]

Herring_LAI <- NULL
```

# Change-points

## Identify change-points

```{r}
### Call function "changepoint_analysis" from functions

### Shetland Orkney
results_cpt <- list()
results_cpt$SHOR <- changepoint_analysis(Herring$SHOR, 
                                          region_name = "Shetland/Orkney",
                                          year_col = "year",
                                          Q = 6,
                                          bcp_threshold = 0.7)
# CPT changepoint indices:  12,   19,   23,   25,   34,   43 
# CPT changepoint years:    1983, 1990, 1994, 1996, 2005, 2014 

# BCP changepoint indices:  12,   19,   23,   31,   34,   43 
# BCP changepoint years:    1983, 1990, 1994, 2002, 2005, 2014 

# Consensus changepoints (± 1 yr, min 5 yr apart): 1983, 1990, 2005, 2014 
# CPT only: 1994, 1996 
# BCP only: 1994, 2002

#---------------------------------------------------------------------

### Buchan
results_cpt$Buchan <- changepoint_analysis(Herring$Buchan, 
                                          region_name = "Buchan",
                                          year_col = "year",
                                          Q = 6,
                                          bcp_threshold = 0.7)
# CPT changepoint indices:  15,   18,   22,   38,   40,   47 
# CPT changepoint years:    1986, 1989, 1993, 2009, 2011, 2018 

## BCP Analysis
# BCP changepoint indices:  18,   21,   23,   39,   46 
# BCP changepoint years:    1989, 1992, 1994, 2010, 2017 

## Consensus Analysis
# Consensus changepoints (± 1 yr, min 5 yr apart): 1989, 2009, 2018 
# CPT only: 1986, 1993, 2011 
# BCP only: 1992, 1994, 2010, 2017

#---------------------------------------------------------------------

### Banks
results_cpt$Banks <- changepoint_analysis(Herring$Banks, 
                                          region_name = "Banks",
                                          year_col = "year",
                                          Q = 6,
                                          bcp_threshold = 0.7)
# CPT changepoint indices:  11,   19,   29,   34,   38,   48 
# CPT changepoint years:    1982, 1990, 2000, 2005, 2009, 2019 

## BCP Analysis
# BCP changepoint indices:  12,   19,   29,   30,   34 
# BCP changepoint years:    1983, 1990, 2000, 2001, 2005 

## Consensus Analysis
# Consensus changepoints (± 1 yr, min 5 yr apart): 1982, 1990, 2000, 2005 
# CPT only: 2009, 2019 
# BCP only: 1983, 2001

#---------------------------------------------------------------------

### Downs
results_cpt$Downs <- changepoint_analysis(Herring$Downs, 
                                          region_name = "Downs",
                                          year_col = "year",
                                          Q = 6,
                                          bcp_threshold = 0.7)
# CPT changepoint indices:  16,   28,   30,   40,   44,   49 
# CPT changepoint years:    1987, 1999, 2001, 2011, 2015, 2020 

## BCP Analysis
# BCP changepoint indices:  30,   40 
# BCP changepoint years:    2001, 2011 

## Consensus Analysis
# Consensus changepoints (± 1 yr, min 5 yr apart): 2001, 2011 
# CPT only: 1987, 1999, 2015, 2020  
```

## Plot change-points

```{r}
### Shetland Orkney
plots_SSB_cpt <- list()
plots_SSB_cpt$SHOR <- plot_SSB_cpt(data = Herring$SHOR, 
              changepoints = results_cpt$SHOR$consensus$changepoint_years,
              ribbon_colors = c("#3e478d", "#5ccdaa", "grey", "#318ca5", "grey"),
              vline_colors = c("black", "grey", "black", "grey"),
              component = "Shetland / Orkney", 
              SSB_column = "SSB_component", 
              l_bnd_column = "l_bnd_component", 
              u_bnd_column = "u_bnd_component",
              show_hlines = FALSE)
plots_SSB_cpt$SHOR

#---------------------------------------------------------------------

### Buchan
plots_SSB_cpt$Buchan <- plot_SSB_cpt(data = Herring$Buchan, 
              changepoints = results_cpt$Buchan$consensus$changepoint_years,
              ribbon_colors = c("#3e478d", "#5ccdaa", "#318ca5", "grey"),
              vline_colors = c("black", "black", "grey"),
              component = "Buchan", 
              SSB_column = "SSB_component", 
              l_bnd_column = "l_bnd_component", 
              u_bnd_column = "u_bnd_component", 
              show_hlines = FALSE)
plots_SSB_cpt$Buchan

#---------------------------------------------------------------------

### Banks
plots_SSB_cpt$Banks <- plot_SSB_cpt(data = Herring$Banks, 
              changepoints = results_cpt$Banks$consensus$changepoint_years,
              ribbon_colors = c("#3e478d", "#5ccdaa", "grey", "#318ca5", "grey"),
              vline_colors = c("black", "grey", "black", "grey"),
              component = "Banks", 
              SSB_column = "SSB_component", 
              l_bnd_column = "l_bnd_component", 
              u_bnd_column = "u_bnd_component", 
              show_hlines = FALSE)
plots_SSB_cpt$Banks

#---------------------------------------------------------------------

### Downs
plots_SSB_cpt$Downs <- plot_SSB_cpt(data = Herring$Downs, 
              changepoints = results_cpt$Downs$consensus$changepoint_years,
              ribbon_colors = c("#3e478d", "#318ca5", "grey"),
              vline_colors = c("black", "grey"),
              component = "Downs", 
              SSB_column = "SSB_component", 
              l_bnd_column = "l_bnd_component", 
              u_bnd_column = "u_bnd_component", 
              show_hlines = FALSE)
plots_SSB_cpt$Downs
```

### Save plots

```{r}
ggsave(filename = file.path("plots/", "SSB_cpt_components.png"),
       plot = grid.arrange(
         plots_SSB_cpt$SHOR + theme(axis.title.x = element_blank(), axis.title.y = element_blank()),
         plots_SSB_cpt$Buchan + theme(axis.title.x = element_blank(), axis.title.y = element_blank()),
         plots_SSB_cpt$Banks + theme(axis.title.x = element_blank(), axis.title.y = element_blank()),
         plots_SSB_cpt$Downs + theme(axis.title.x = element_blank(), axis.title.y = element_blank()),
         ncol = 1,
         bottom = "Year",
         left = "SSB in million t"),
       bg = "white",
       width = 7,
       height = 14,
       dpi = 300)
```

### Save plot as grid

```{r}
#### CPT plot for full stock as well as Herring_full must be loaded from "data_analysis.Rmd"
#### Plot SSB cpt with parameter "plot_for_grid = TRUE"
plots_F <- list()
plots_R <- list()

# Full Stock plots
plot_F_full <- plot_F_cpt(data = Herring_full,
                          changepoints = c(1966, 1983, 2000),
                          ribbon_colors = c("#201124", "#3e478d", "grey", "#318ca5"),
                          vline_colors = c("black", "grey", "black"),
                          component = "Full Stock")

plot_R_full <- plot_Recruitment_cpt(data = Herring_full,
                                    changepoints = c(1966, 1983, 2000),
                                    ribbon_colors = c("#201124", "#3e478d", "grey", "#318ca5"),
                                    vline_colors = c("black", "grey", "black"),
                                    component = "Full Stock")

# Shetland Orkney plots
plots_F$SHOR <- plot_F_cpt(data = Herring$SHOR,
                           changepoints = results_cpt$SHOR$consensus$changepoint_years,
                           ribbon_colors = c("#3e478d", "#5ccdaa", "grey", "#318ca5", "grey"),
                           vline_colors = c("black", "grey", "black", "grey"),
                           component = "Shetland / Orkney")

plots_R$SHOR <- plot_Recruitment_cpt(data = Herring$SHOR,
                                     changepoints = results_cpt$SHOR$consensus$changepoint_years,
                                     ribbon_colors = c("#3e478d", "#5ccdaa", "grey", "#318ca5", "grey"),
                                     vline_colors = c("black", "grey", "black", "grey"),
                                     component = "Shetland / Orkney")

# Buchan plots
plots_F$Buchan <- plot_F_cpt(data = Herring$Buchan,
                             changepoints = results_cpt$Buchan$consensus$changepoint_years,
                             ribbon_colors = c("#3e478d", "#5ccdaa", "#318ca5", "grey"),
                             vline_colors = c("black", "black", "grey"),
                             component = "Buchan")

plots_R$Buchan <- plot_Recruitment_cpt(data = Herring$Buchan,
                                       changepoints = results_cpt$Buchan$consensus$changepoint_years,
                                       ribbon_colors = c("#3e478d", "#5ccdaa", "#318ca5", "grey"),
                                       vline_colors = c("black", "black", "grey"),
                                       component = "Buchan")

# Banks plots
plots_F$Banks <- plot_F_cpt(data = Herring$Banks,
                            changepoints = results_cpt$Banks$consensus$changepoint_years,
                            ribbon_colors = c("#3e478d", "#5ccdaa", "grey", "#318ca5", "grey"),
                            vline_colors = c("black", "grey", "black", "grey"),
                            component = "Banks")

plots_R$Banks <- plot_Recruitment_cpt(data = Herring$Banks,
                                      changepoints = results_cpt$Banks$consensus$changepoint_years,
                                      ribbon_colors = c("#3e478d", "#5ccdaa", "grey", "#318ca5", "grey"),
                                      vline_colors = c("black", "grey", "black", "grey"),
                                      component = "Banks")

# Downs plots
plots_F$Downs <- plot_F_cpt(data = Herring$Downs,
                            changepoints = results_cpt$Downs$consensus$changepoint_years,
                            ribbon_colors = c("#3e478d", "#318ca5", "grey"),
                            vline_colors = c("black", "grey"),
                            component = "Downs")

plots_R$Downs <- plot_Recruitment_cpt(data = Herring$Downs,
                                      changepoints = results_cpt$Downs$consensus$changepoint_years,
                                      ribbon_colors = c("#3e478d", "#318ca5", "grey"),
                                      vline_colors = c("black", "grey"),
                                      component = "Downs")

# Create the 5x3 grid with row labels and column headers
library(grid)

# Create individual text grobs for row labels
row_label1 <- textGrob("Full Stock", rot = 90, gp = gpar(fontsize = 12, fontface = "bold"))
row_label2 <- textGrob("Shetland/Orkney", rot = 90, gp = gpar(fontsize = 12, fontface = "bold"))
row_label3 <- textGrob("Buchan", rot = 90, gp = gpar(fontsize = 12, fontface = "bold"))
row_label4 <- textGrob("Banks", rot = 90, gp = gpar(fontsize = 12, fontface = "bold"))
row_label5 <- textGrob("Downs", rot = 90, gp = gpar(fontsize = 12, fontface = "bold"))

# Create individual text grobs for column headers
col_header1 <- textGrob("Fishing Mortality", gp = gpar(fontsize = 12, fontface = "bold"))
col_header2 <- textGrob("SSB with Changepoints", gp = gpar(fontsize = 12, fontface = "bold"))
col_header3 <- textGrob("Recruitment", gp = gpar(fontsize = 12, fontface = "bold"))

# Create empty grob for top-left corner
empty_grob <- nullGrob()

# Arrange plots with labels
grid_plot <- grid.arrange(
  # Header row
  empty_grob, col_header1, col_header2, col_header3,
  
  # Row 1: Full Stock
  row_label1, plot_F_full, plot_SSB_cpt_full, plot_R_full,
  
  # Row 2: Shetland Orkney
  row_label2, plots_F$SHOR, plots_SSB_cpt$SHOR, plots_R$SHOR,
  
  # Row 3: Buchan
  row_label3, plots_F$Buchan, plots_SSB_cpt$Buchan, plots_R$Buchan,
  
  # Row 4: Banks
  row_label4, plots_F$Banks, plots_SSB_cpt$Banks, plots_R$Banks,
  
  # Row 5: Downs
  row_label5, plots_F$Downs, plots_SSB_cpt$Downs, plots_R$Downs,
  
  nrow = 6, ncol = 4,
  widths = c(0.15, 1, 1, 1),
  heights = c(0.1, 1, 1, 1, 1, 1))

ggsave(filename = file.path("plots/", "cpt_grid.png"),
       plot = grid_plot,
       bg = "white",
       width = 12,
       height = 10,
       dpi = 300)
```

# Hysteresis

## Analysis

```{r}
### Examine for time lag
ccf(Herring$SHOR$SSB_component, Herring$SHOR$F, type = "correlation") # 1 year lag
Herring$SHOR$SSB_lag <- lag(Herring$SHOR$SSB_component, 1)

ccf(Herring$Buchan$SSB_component, Herring$Buchan$F, type = "correlation") # 3 years lag
Herring$Buchan$SSB_lag <- lag(Herring$Buchan$SSB_component, 3)

ccf(Herring$Banks$SSB_component, Herring$Banks$F, type = "correlation") # 5 years lag
Herring$Banks$SSB_lag <- lag(Herring$Banks$SSB_component, 5)

ccf(Herring$Downs$SSB_component, Herring$Downs$F, type = "correlation") # 1 year lag
Herring$Downs$SSB_lag <- lag(Herring$Downs$SSB_component, 1)

#---------------------------------------------------------------------
### Call function "breakpoint_analysis"

### Shetland Orkney
results_brkpt <- list()
results_brkpt$SHOR <- breakpoint_analysis(Herring$SHOR, "SSB_component", "F", "year",
                                               lag_years = 1,
                                               region_name = "Shetland Orkney")

# Optimal number of breaks: 5 
# Best breakpoint F values:
# 0.28 0.29 0.189 0.29 0.22 
# Best breakpoint years:
# 1983, 1990, 1997, 2005, 2015
#---------------------------------------------------------------------

### Buchan
results_brkpt$Buchan <- breakpoint_analysis(Herring$Buchan, "SSB_component", "F", "year", 
                                    lag_years = 3, 
                                    region_name = "Buchan")
# Optimal number of breaks: 3
# Best breakpoint F values:
# 0.29 0.189 0.184 
# Best breakpoint years:
# 1990, 1997, 2012 
#---------------------------------------------------------------------

### Banks
results_brkpt$Banks <- breakpoint_analysis(Herring$Banks, "SSB_component", "F", "year", 
                                    lag_years = 5, 
                                    region_name = "Banks")
# Optimal number of breaks: 2
# Best breakpoint F values:
# 0.39 0.29 
# Best breakpoint years:
# 1988, 2005 
#---------------------------------------------------------------------

### Downs
results_brkpt$Downs <- breakpoint_analysis(Herring$Downs, "SSB_component", "F", "year", 
                                    lag_years = 1, 
                                    region_name = "Downs")
# Optimal number of breaks: 4 
# Best breakpoint F values:
# 0.41 0.171 0.073 0.24 
# Best breakpoint years:
# 1987, 2002, 2009, 2016 
```

## Plotting

```{r}
### Call function plot_hysteresis 
plots_hysteresis <- list()

plots_hysteresis$SHOR <- plot_hysteresis(Herring$SHOR, results_brkpt$SHOR$break_years, "Shetland Orkneys", show_msy_btrigger = FALSE)
plots_hysteresis$SHOR

plots_hysteresis$Buchan <- plot_hysteresis(Herring$Buchan, results_brkpt$Buchan$break_years, "Buchan", show_msy_btrigger = FALSE)
plots_hysteresis$Buchan

plots_hysteresis$Banks <- plot_hysteresis(Herring$Banks, results_brkpt$Banks$break_years, "Banks", show_msy_btrigger = FALSE)
plots_hysteresis$Banks

plots_hysteresis$Downs <- plot_hysteresis(Herring$Downs, results_brkpt$Downs$break_years, "Downs", show_msy_btrigger = FALSE)
plots_hysteresis$Downs
```

### save plot

```{r}
ggsave(filename = file.path("plots/", "hysteresis_components.png"),
       plot = grid.arrange(
         plots_hysteresis$SHOR + theme(axis.title.x = element_blank(), axis.title.y = element_blank()),
         plots_hysteresis$Buchan + theme(axis.title.x = element_blank(), axis.title.y = element_blank()),
         plots_hysteresis$Banks + theme(axis.title.x = element_blank(), axis.title.y = element_blank()),
         plots_hysteresis$Downs + theme(axis.title.x = element_blank(), axis.title.y = element_blank()),
         ncol = 1,
         bottom = "F",
         left = "SSB in million t"),
       bg = "white",
       width = 7,
       height = 14,
       dpi = 300)
```

# SRR Non-Stationary

## Analysis

```{r}
### Load model comparison from model_comp_functions.R 
source("R/model_comp_functions.R")

### Shetland Orkney
#### Compare different models
models_SRR <- list()

models_SRR$SHOR <- run_srr_analysis(
  data_for_srr = Herring$SHOR,
  recruit_col = "Recruitment",
  ssb_col = "SSB_component",
  max_breaks = 5,
  use_bic = TRUE)

print(models_SRR$SHOR$comparison_table)
#               Model          AIC     RMSE R_squared
#        independence 1.795652e+03  7197567 0.3897771
#       beverton_holt 1.138750e+02  8004318 0.3220916
#              ricker 1.152775e+02  7902179 0.3149778
#   segmented_regular 1.791667e+03  6665647 0.4766386
#       segmented_log 1.124631e+02 14069690 0.4168969
#  segmented_negbinom 1.758980e+03  6990494        NA
#         strucchange 1.743655e+03  3889912 0.8217635
#        glm_gaussian 1.795652e+03  7197567        NA
#         glm_poisson 2.137039e+08  6957747        NA
#    glm_quasipoisson           NA  6957747        NA
#        glm_negbinom 1.763447e+03  6955796        NA

##### strucchange lowest RMSE.

### Prep data for LOOCV function
dat_SHOR <- Herring$SHOR %>%
  mutate(R_log = log(Recruitment),
         SSB_log = log(SSB_component)) %>%
  dplyr::select(year, Recruitment, SSB_component, R_log, SSB_log) %>%
  na.omit() %>%
  setNames(c("Year", "R", "SSB", "R_log", "SSB_log")) %>%
  as.data.frame()

### Call function "cross_valid" for performing loocv for all models
rmse_mean_SHOR <- cross_valid(dataset = dat_SHOR)
#         linear    beverton    ricker      segmented   seg.log     segm.glm    strucchange
# TEST:   6032494   5917938     5996407     5906258     5705905     5919392     10051737
# TRAIN:  7193145   7998380     7896592     6659682     6947653     6985389     3945464

#### strucchange validated by loocv.

### Call function "srr_breakpoint_analysis" to extract SSR breakpoints
results_SRR <- list()
results_SRR$SHOR <- srr_breakpoint_analysis(Herring$SHOR, "SSB_component", "Recruitment", "year", "Shetland Orkney")

# Optimal number of breaks: 3 
# Best breakpoint SSB values:
# 148853.8, 505309.4, 1201916.7 
# Best breakpoint years:
# 1980, 1987, 2001 

#---------------------------------------------------------------------

### Buchan
#### Compare different models
models_SRR$Buchan <- run_srr_analysis(
  data_for_srr = Herring$Buchan,
  recruit_col = "Recruitment",
  ssb_col = "SSB_component",
  max_breaks = 5,
  use_bic = TRUE)

print(models_SRR$Buchan$comparison_table)
#               Model          AIC    RMSE R_squared
#        independence 1.773301e+03 5805618 0.3996297
#       beverton_holt 1.067257e+02 6173465 0.3797114
#              ricker 1.089596e+02 6148872 0.3643869
#   segmented_regular 1.776181e+03 5743466 0.4124155
#       segmented_log 1.083281e+02 9688514 0.8613104
#  segmented_negbinom 1.671189e+03 6048104        NA
#         strucchange 1.678348e+03 2075984 0.9232338
#        glm_gaussian 1.773301e+03 5805618        NA
#         glm_poisson 2.118232e+08 6211740        NA
#    glm_quasipoisson           NA 6211740        NA
#        glm_negbinom 1.704921e+03 9416817        NA

##### strucchange lowest RSME.

#### Prep data for LOOCV function
dat_Buchan <- Herring$Buchan %>%
  mutate(R_log = log(Recruitment),
         SSB_log = log(SSB_component)) %>%
  dplyr::select(year, Recruitment, SSB_component, R_log, SSB_log) %>%
  na.omit() %>%
  setNames(c("Year", "R", "SSB", "R_log", "SSB_log")) %>%
  as.data.frame()

#### Call function "cross_valid" for performing loocv for all models
rmse_mean_Buchan <- cross_valid(dataset = dat_Buchan)

#         linear    beverton    ricker    segmented   seg.log     segm.glm    strucchange
# TEST:   3896841   3509676     3594420   3800680     3380904     4106180     8088465
# TRAIN:  5799156   6165425     6142350   5736075     6092542     5932873     2064443

#### strucchange validated by loocv.

#### Call function "srr_breakpoint_analysis" to extract SSR breakpoints
results_SRR$Buchan <- srr_breakpoint_analysis(Herring$Buchan, "SSB_component", "Recruitment", "year", "Buchan")

# Optimal number of breaks: 3 
# Best breakpoint SSB values:
# 147574.4, 1257071.9, 123660.5 
# Best breakpoint years:
# 1983, 1991, 2001 

#---------------------------------------------------------------------

### Banks
#### Compare different models
models_SRR$Banks <- run_srr_analysis(
  data_for_srr = Herring$Banks,
  recruit_col = "Recruitment",
  ssb_col = "SSB_component",
  max_breaks = 5,
  use_bic = TRUE)

print(models_SRR$Banks$comparison_table)
#               Model          AIC    RMSE R_squared
#        independence 1.711783e+03 3213326 0.1395247
#       beverton_holt 9.514737e+01 3182347 0.1989981
#              ricker 9.391551e+01 3135145 0.2289354
#   segmented_regular 1.708380e+03 2992557 0.2536997
#       segmented_log 9.714308e+01 5459619 0.4719001
#  segmented_negbinom 1.659950e+03 3022782        NA
#         strucchange 1.616282e+03 1142987 0.8911292
#        glm_gaussian 1.711783e+03 3213326        NA
#         glm_poisson 1.020982e+08 3274292        NA
#    glm_quasipoisson           NA 3274292        NA
#        glm_negbinom 1.672878e+03 3351264        NA

##### strucchange lowest RMSE.

#### Prep data for LOOCV function
dat_Banks <- Herring$Banks %>%
  mutate(R_log = log(Recruitment),
         SSB_log = log(SSB_component)) %>%
  dplyr::select(year, Recruitment, SSB_component, R_log, SSB_log) %>%
  na.omit() %>%
  setNames(c("Year", "R", "SSB", "R_log", "SSB_log")) %>%
  as.data.frame()

#### Call function "cross_valid" for performing loocv for all models
rmse_mean_Banks <- cross_valid(dataset = dat_Banks)

#         linear    beverton    ricker    segmented   seg.log     segm.glm    strucchange
# TEST:   2298870   1970034     1954005   2399083     2038932     2370782     4248983
# TRAIN:  3211518   3180706     3133516   2988736     3112284     3020506     1154869

#### strucchange validated by loocv. 

#### Call function "srr_breakpoint_analysis" to extract SSR breakpoints
results_SRR$Banks <- srr_breakpoint_analysis(Herring$Banks, "SSB_component", "Recruitment", "year", "Banks")

# Optimal number of breaks: 3 
# Best breakpoint SSB values:
# 38326.5, 307682.7, 303694 
# Best breakpoint years:
# 1980, 1987, 2001 

#---------------------------------------------------------------------

### Downs
#### Compare different models
models_SRR$Downs <- run_srr_analysis(
  data_for_srr = Herring$Downs,
  recruit_col = "Recruitment",
  ssb_col = "SSB_component",
  max_breaks = 5,
  use_bic = TRUE)

print(models_SRR$Downs$comparison_table)
#               Model          AIC    RMSE R_squared
#        independence 1.650648e+03 1785101 0.6819995
#       beverton_holt 1.647558e+03 1732842 0.7030111
#              ricker 6.888289e+01 1937852 0.6302762
#   segmented_regular 1.644580e+03 1620395 0.7379742
#       segmented_log 4.472053e+01 5479861 0.9608838
#  segmented_negbinom 1.631792e+03 1612934        NA
#         strucchange 1.621802e+03 1159822 0.8657591
#        glm_gaussian 1.650648e+03 1785101        NA
#         glm_poisson 5.589560e+07 1890595        NA
#    glm_quasipoisson           NA 1890595        NA
#        glm_negbinom 1.681034e+03 2018424        NA

##### strucchange lowest RMSE.

#### Prep data for LOOCV function
dat_Downs <- Herring$Downs %>%
  mutate(R_log = log(Recruitment),
         SSB_log = log(SSB_component)) %>%
  dplyr::select(year, Recruitment, SSB_component, R_log, SSB_log) %>%
  na.omit() %>%
  setNames(c("Year", "R", "SSB", "R_log", "SSB_log")) %>%
  as.data.frame()

#### Call function "cross_valid" for performing loocv for all models
rmse_mean_Downs <- cross_valid(dataset = dat_Downs)

#         linear    beverton    ricker      segmented   seg.log     segm.glm    strucchange
# TEST:   10947162  9919600     15101560    6227837     5940221     5632788     7576975
# TRAIN:  1784159   1771427     1936651     1619286     1688248     1611886     1237352

#### segmented outperform classical models for train data

#### Call function "srr_breakpoint_analysis" to extract SSR breakpoints
results_SRR$Downs <- srr_breakpoint_analysis(Herring$Downs, "SSB_component", "Recruitment", "year", "Downs")

# Optimal number of breaks: 4 
# Best breakpoint SSB values:
# 17120.8, 213659.7, 565941.9, 435906.7 
# Best breakpoint years:
# 1980, 2000, 2007, 2014 
```

## Plotting

```{r}
### Call "plot_SRR" function from functions.R
### Shetland Orkney
plots_SRR <- list()
plots_SRR$SHOR <- plot_SRR(Herring$SHOR, break_years = results_SRR$SHOR$break_years,
                          title_stock = "Shetland Orkney", 
                          used_model = "strucchange", 
                          ssb_col = "SSB_component",
                          show_Blim = FALSE,
                          nudge_params = list(
                            list(nudge_y = 9, nudge_x = -0.15),    # first year
                            list(nudge_y = 0, nudge_x = -0.2),    # breakpoint
                            list(nudge_y = 20, nudge_x = 0),     # last year
                            list(nudge_y = -0, nudge_x = 0.2)))   # more breakpoints
plots_SRR$SHOR

#---------------------------------------------------------------------

### Buchan
plots_SRR$Buchan <- plot_SRR(Herring$Buchan, break_years = results_SRR$Buchan$break_years,
                          title_stock = "Buchan", 
                          used_model = "strucchange", 
                          ssb_col = "SSB_component",
                          show_Blim = FALSE,
                          nudge_params = list(
                            list(nudge_y = 5, nudge_x = 0),    # first year
                            list(nudge_y = 5, nudge_x = 0),    # breakpoint
                            list(nudge_y = 25, nudge_x = 0),     # last year
                            list(nudge_y = 10, nudge_x = -0.1)))   # more breakpoints
plots_SRR$Buchan

#---------------------------------------------------------------------

### Banks
plots_SRR$Banks <- plot_SRR(Herring$Banks, break_years = results_SRR$Banks$break_years,
                          title_stock = "Banks", 
                          used_model = "strucchange", 
                          ssb_col = "SSB_component",
                          show_Blim = FALSE,
                          nudge_params = list(
                            list(nudge_y = 10, nudge_x = 0),    # first year
                            list(nudge_y = 8, nudge_x = 0),    # breakpoint
                            list(nudge_y = 15, nudge_x = 0),     # last year
                            list(nudge_y = 0, nudge_x = 0.05)))   # more breakpoints
plots_SRR$Banks

#---------------------------------------------------------------------

### Downs
plots_SRR$Downs <- plot_SRR(Herring$Downs, break_years = results_SRR$Downs$break_years,
                          title_stock = "Downs", 
                          used_model = "strucchange", 
                          ssb_col = "SSB_component",
                          show_Blim = FALSE,
                          nudge_params = list(
                            list(nudge_y = 7, nudge_x = 0),    # first year
                            list(nudge_y = 4, nudge_x = 0),    # breakpoint
                            list(nudge_y = 7, nudge_x = 0),     # last year
                            list(nudge_y = 5, nudge_x = 0)))   # more breakpoints
plots_SRR$Downs
```

#### save plot

```{r}
ggsave(filename = file.path("plots/", "SRR_components.png"),
       plot = grid.arrange(
         plots_SRR$SHOR + theme(axis.title.x = element_blank(), axis.title.y = element_blank()),
         plots_SRR$Buchan + theme(axis.title.x = element_blank(), axis.title.y = element_blank()),
         plots_SRR$Banks + theme(axis.title.x = element_blank(), axis.title.y = element_blank()),
         plots_SRR$Downs + theme(axis.title.x = element_blank(), axis.title.y = element_blank()),
         ncol = 1,
         bottom = "SSB in million t",
         left = "R in billions"),
       bg = "white",
       width = 7,
       height = 14,
       dpi = 300)
```

# tGAM

```{r}
### Load env data
load("data/env_df_subset.Rdata")
load("data/env_df_full.Rdata")

### Call "run_threshold_analysis" from functions and extract results (below)
results_tgam <- list()
#### SHOR
results_tgam$SHOR <- run_threshold_analysis(Herring$SHOR, 
                                            env_df_subset, 
                                            region_name = "Shetland_Orkney",
                                            aggregation_mode = "autumn", 
                                            test_variables = c("Mean_SST", "Mean_SSS"))

results_tgam$SHOR_larv <- run_threshold_analysis(Herring$SHOR, 
                                            env_df_full,
                                            aggregation_mode = "winter", 
                                            test_variables = c("Mean_SST", "Mean_SSS"))

# results_tgam[["SHOR"]][["summary_tables"]][["autumn"]]
#   Variable  n edf_before edf_after p_value_min Threshold Threshold_accepted
#   Mean_SST 52      0.667     0.237       0.097      11.0    No tGAM (LOOCV)
#   Mean_SSS 52      0.667     0.000       0.219      35.1    No tGAM (LOOCV)

# results_tgam[["SHOR_larv"]][["summary_tables"]][["winter"]]
#   Variable  n edf_before edf_after p_value_min Threshold Threshold_accepted
#   Mean_SST 52      0.667     0.991       0.052       7.7    No tGAM (LOOCV)
#   Mean_SSS 52      0.667     0.000       0.030      34.3    No tGAM (LOOCV)

#### no threshold accepted.

#---------------------------------------------------------------------

#### Buchan
results_tgam$Buchan <- run_threshold_analysis(Herring$Buchan, 
                                            env_df_subset, 
                                            region_name = "Buchan",
                                            aggregation_mode = "autumn", 
                                            test_variables = c("Mean_SST", "Mean_SSS"))

results_tgam$Buchan_larv <- run_threshold_analysis(Herring$Buchan, 
                                            env_df_full,
                                            aggregation_mode = "winter", 
                                            test_variables = c("Mean_SST", "Mean_SSS"))

# results_tgam[["Buchan"]][["summary_tables"]][["autumn"]]
#   Variable  n edf_before edf_after p_value_min Threshold Threshold_accepted
#   Mean_SST 52      0.667     0.754    6.12e-04      11.2    No tGAM (LOOCV)
#   Mean_SSS 52      0.667     0.924       0.002      34.8    No tGAM (LOOCV)

# results_tgam[["Buchan_larv"]][["summary_tables"]][["winter"]]
#   Variable  n edf_before edf_after p_value_min Threshold Threshold_accepted
#   Mean_SST 52      0.667     0.000    1.30e-17       7.1    No tGAM (LOOCV)
#   Mean_SSS 52      0.667     0.384    4.55e-06      34.4    No tGAM (LOOCV)

#### no threshold accepted.

#---------------------------------------------------------------------

#### Banks
results_tgam$Banks <- run_threshold_analysis(Herring$Banks, 
                                            env_df_subset, 
                                            region_name = "Banks",
                                            aggregation_mode = "autumn", 
                                            test_variables = c("Mean_SST", "Mean_SSS"))

results_tgam$Banks_larv <- run_threshold_analysis(Herring$Banks, 
                                            env_df_full,
                                            aggregation_mode = "winter", 
                                            test_variables = c("Mean_SST", "Mean_SSS"))

# results_tgam[["Banks"]][["summary_tables"]][["autumn"]]
#   Variable  n edf_before edf_after p_value_min Threshold Threshold_accepted
#   Mean_SST 52      0.667     0.939    2.86e-07      12.1                Yes
#   Mean_SSS 52      0.667     0.000    8.56e-09      34.5    No tGAM (LOOCV)

# results_tgam[["Banks_larv"]][["summary_tables"]][["winter"]]
#   Variable  n edf_before edf_after p_value_min Threshold Threshold_accepted
#   Mean_SST 52      0.667     0.912    8.66e-08       7.2    No tGAM (LOOCV)
#   Mean_SSS 52      0.667     0.995    1.90e-10      34.4    No tGAM (LOOCV)

#### SST threshold accepted for autumn.

png(filename = "plots/tGAM/SST_Banks_autumn.png", width = 1500, height = 1000, res = 300)
plot_gcv_Banks_SST_autumn <- plot_gcv_threshold(results_tgam$Banks$autumn$SST, "SST-Banks", "(Autumn)")
dev.off()

#### Threshold confirmed by gcv valley.

#---------------------------------------------------------------------

#### Downs
results_tgam$Downs <- run_threshold_analysis(Herring$Downs, 
                                            env_df_subset, 
                                            region_name = "Downs",
                                            aggregation_mode = "autumn", 
                                            test_variables = c("Mean_SST", "Mean_SSS"))

results_tgam$Downs_larv <- run_threshold_analysis(Herring$Downs, 
                                            env_df_full,
                                            aggregation_mode = "winter", 
                                            test_variables = c("Mean_SST", "Mean_SSS"))

# results_tgam[["Downs"]][["summary_tables"]][["autumn"]]
#   Variable  n edf_before edf_after p_value_min Threshold Threshold_accepted
#   Mean_SST 52      0.667     0.901    3.12e-04      14.4    No tGAM (LOOCV)
#   Mean_SSS 52      0.667     0.956       0.803      33.8    No tGAM (LOOCV)

# results_tgam[["Downs_larv"]][["summary_tables"]][["winter"]]
#   Variable  n edf_before edf_after p_value_min Threshold Threshold_accepted
#   Mean_SST 52      0.667     0.759    3.88e-05       7.7    No tGAM (LOOCV)
#   Mean_SSS 52      0.667     0.986    9.05e-07      34.4    No tGAM (LOOCV)

####  no threshold accepted.
```

## Plot

```{r}
### Prep data for plotting
tgam_input <- Herring$Banks %>%
  dplyr::select(year, SSB_component, Recruitment) %>%
  left_join(
    env_df_subset %>%
      filter(Region == "Banks", Season == "Autumn") %>%
      dplyr::select(year, Mean_SST),
    by = "year"
  ) %>%
  drop_na() %>%
  mutate(SSB_lag = lag(SSB_component, n = 3)) %>%
  drop_na() %>%
  arrange(SSB_lag) %>%
  rename(Year = year, SSB = SSB_component)

### Plot using "plot_tgam" from funtions
plot_tgam_banks <- plot_tgam_complete(tgam_input, threshold = 12.1, env_var = "Mean_SST")

### save plot
ggsave(filename = file.path("plots/tGAM", "Banks_SST.png"),
       plot = plot_tgam_banks,
       bg = "white",
       width = 10,
       height = 7,
       dpi = 300)
```
